config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'
  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
      get 'lady'
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      resources :buyers, only: [:index] do
        collection do
          post 'pay', to: 'buyers#pay'
          get 'done', to: 'buyers#done'
        end
      end
    end
  end
  resources :users, only: [:show, :edit]
  resources :addresses, only: [:new, :create]
  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end
end

app/views/modules/_mypage-left.html.haml
.left-content
  .mypage-navigation
    %ul.mypage-nav__list
      %li
        = link_to root_path, method: :get, class: "mypage-nav__list__item" do
          トップページへ
          %i.fa.fa-chevron-right

      %li
        = link_to new_item_path, method: :get, class: "mypage-nav__list__item" do
          出品ページへ
          %i.fa.fa-chevron-right

      %li
        = link_to "#", class: "mypage-nav__list__item" do
          出品中ページへ
          %i.fa.fa-chevron-right

      %li
        = link_to "#", class: "mypage-nav__list__item" do
          出品・売却済みページへ
          %i.fa.fa-chevron-right

      %li
        = link_to "#", class: "mypage-nav__list__item" do
          購入済み商品ページへ
          %i.fa.fa-chevron-right

  .mypage-navigation
    .mypage-nav__head 設定
    %ul.mypage-nav__list
      %li
        = link_to new_address_path, method: :get, class: "mypage-nav__list__item" do
          本人情報
          %i.fa.fa-chevron-right
      %li
        = link_to card_index_path, method: :post, class: "mypage-nav__list__item" do
          支払い方法
          %i.fa.fa-chevron-right
      %li
        = link_to edit_user_path(current_user), method: :get, class: "mypage-nav__list__item" do
          メール/パスワード
          %i.fa.fa-chevron-right
      %li
        = link_to destroy_user_session_path, method: :delete , class: "mypage-nav__list__item" do
          ログアウト
          %i.fa.fa-chevron-right