config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'
  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
      get 'lady'
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      resources :buyers, only: [:index] do
        collection do
          post 'pay', to: 'buyers#pay'
          get 'done', to: 'buyers#done'
        end
      end
    end
  end
  resources :users, only: [:show, :edit]
  resources :addresses, only: [:new, :create]
  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  validates :name, presence: true, length: { maximum: 40 }
  validates :category_id, :status_id, :burden_id, :area_id, :days_to_ship_id, :saler_id,presence: true
  validates :text, presence: true, length: { maximum: 1000 }
  validates :selling_price, presence: true, numericality: { greater_than: 299, less_than:10000000 }
  validates :images, presence: true
  has_one :buyer
  belongs_to :category
  belongs_to :user, optional: true
  belongs_to :saler, class_name: "User", optional: true
  belongs_to :buyer, class_name: "User", optional: true
  belongs_to_active_hash :area
  belongs_to_active_hash :burden
  belongs_to_active_hash :days_to_ship
  belongs_to_active_hash :status

  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true

  scope :search, -> (search){ where('text LIKE(?)', "%#{search}%") }

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: [:edit]
  before_action :set_item, only: [:show, :edit, :update]
  before_action :move_to_root, only: [:new, :edit, :update]
  before_action :correct_user, only: [:edit, :update]
  before_action :user_address, only: [:new]


  def index
    @items = Item.all
    sold_out_item_ids = Buyer.all.pluck(:item_id)
    @item = Item.order(id: "DESC").where.not(id: sold_out_item_ids).first(3)
  end

  def show
    @item = Item.find(params[:id])
    @next_item = Item.where("id > ?", @item.id).order("id ASC").first
    @prev_item = Item.where("id < ?", @item.id).order("id DESC").first
    @my_item = Item.where(saler_id: @item.saler_id)
  end

  def new
    @item = Item.new
    @item.images.new
    
    def get_category_children
      @category_children = Category.find_by(id: "#{params[:parent_id]}", ancestry: nil).children
    end
  
    def get_category_grandchildren
      @category_grandchildren = Category.find("#{params[:child_id]}").children
    end
  end


  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path, notice: "出品しました"
    else
      redirect_to new_item_path, alert: "出品できません。入力必須項目を確認してください"
    end
  end

  def edit
    @category_parent_array = Category.where(ancestry: nil)
    @grandchild_category = @item.category
    @child_category = @item.category.parent
    @parent_category = @item.category.root

    @child = @parent_category.children
    @grandchild = @child_category.children
  end


  def update
    if @item.update(item_params)
      redirect_to item_path(@item.id), notice: "編集しました"
    else
      redirect_to edit_item_path, alert: "編集できません。入力必須項目を確認してください"
    end
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
  end

  def search
    @items = Item.search(params[:search]).order(id: "DESC")
  end

  def lady
    @items = Item.where(category: 1..199)
  end


  
  private

  def item_params
    params.require(:item).permit(:name, :text, :status_id, :burden_id, :area_id, :days_to_ship_id, :selling_price, :category_id, :brand, images_attributes: [:image, :_destroy, :id]).merge(saler_id: current_user.id) 
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def move_to_root
    if user_signed_in?
    else
      flash[:alert] = "出品するためにはユーザー登録が必要です"
      redirect_to root_path
    end
  end

  def correct_user
    if @current_user.id !=  @item.saler_id
     redirect_to root_path
    end
  end

  def user_address
    redirect_to root_path, alert:"出品するためには本人情報の登録が必要です" if @current_user.address.blank?
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
.n__container
  .n__logo
    = link_to image_tag('/logo.png', :width => '170', :height => '60'), root_path
      
  .n__form__container
    =form_for @item do |f|
      %ul
        .n__image__container
          %p.message 商品出品画像（必須）
          %p.message 最大5枚までアップロード出来ます
          .post__drop__box__container
            .prev-content
            .label-content
              %label{for: "item_images_attributes_0_image", class: "label-box", id: "label-box--0"}
                %pre.label-box__text-visible クリックしてファイルをアップロード
            .hidden-content
              = f.fields_for :images do |i|
                = i.file_field :image, class: "hidden-field"
                %input{class:"hidden-field", type: "file", name: "item[images_attributes][1][image]", id: "item_images_attributes_1_image" }
                %input{class:"hidden-field", type: "file", name: "item[images_attributes][2][image]", id: "item_images_attributes_2_image" }
                %input{class:"hidden-field", type: "file", name: "item[images_attributes][3][image]", id: "item_images_attributes_3_image" }
                %input{class:"hidden-field", type: "file", name: "item[images_attributes][4][image]", id: "item_images_attributes_4_image" }
        .n__item__container
          %p.message 商品名（必須）
          = f.text_field :name, class: "name-box",  placeholder: "商品名（必須 40文字まで)"
          %p.message 商品の説明（必須）
          = f.text_area :text, class: "description-box",  cols: "60", rows: "7", placeholder: "商品の説明(必須1,000文字以内)(色、素材、重さ、定価、注意点など)                      例）2010年頃には一万円で購入したジャケットです。ライトグレーではありません。あわせやすいのでお勧めです。"
        .n__details__container
          %p.message カテゴリー（必須)
          .sell-category-box
            = f.collection_select :category_id, @category_parent_array, :id, :name, {prompt: "---"}, {class: 'sell__item-category', id: 'parent_category'}
          %p.message ブランド (任意)
          = f.text_field :brand, class: "brand-box", placeholder: "例) シャネル"
          %p.message 商品の状態（必須）
          = f.collection_select :status_id, Status.all, :id, :name, {}, {class: "select-box"}
        .n__post__container
          %p.message 配送について
          %p.message 配送料の負担（必須）
          = f.collection_select :burden_id, Burden.all, :id, :name, { include_blank: true, selected: 1 }, {class: "select-box"}
          %p.message 発送元の地域（必須）
          = f.collection_select :area_id, Area.all, :id, :name, { include_blank: true, selected: 1 }, {class: "select-box"}
          %p.message 発送までの日数（必須）
          = f.collection_select :days_to_ship_id, DaysToShip.all, :id, :name, { include_blank: true, selected: 1 }, {class:"select-box"}
        .n__price__container
          %p.message 価格（¥300〜9,999,999）
          .content-flex
            .message 販売価格（必須）
            .price
              %span ¥
              =f.number_field :selling_price, class: "item-price-title-text-b-field-text", min: "300", max: "9999999", placeholder: "0", id: "price_calc"
      .n__submit__container
        .button
          =f.submit "商品を出品する", class: "exhibition"
        .back
          = link_to "戻る", root_path
        
      .n__attention__container
        %p.message 禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。
  .n__end__logo__container
    .n__end__logo__container__end__logo
      = link_to image_tag('/logo.png', :width => '170', :height => '60'), root_path
      %p ©️Frima.inc 

app/views/items/_item-btn.html.haml
= link_to  new_item_path, class: 'submit-btn-link' do
  .sellbtn
    %span
      .sellbtn__text
        出品する
      = image_tag '/icon_camera.png', size: '70x70'

app/views/items/_main-footer.html.haml
.main-fotter
  .main-fotter_container
    %ul
      %li.main-fotter-cell.about-mercari
        %h2.main-fotter__header
          フリマについて
        %ul
          %li
            = link_to "#" do
              会社概要（運営会社)
          %li
            = link_to "#" do
              採用情報
          %li
            = link_to "#" do
              プレスリリース
          %li
            = link_to "#" do
              公式ブログ
          %li
            = link_to "#" do
              フリマロゴ利用ガイドライン
          %li
            = link_to "https://twitter.com/explore" do
              %i.fa.fa-twitter.fa-lg.icon-twitter
            = link_to "https://www.facebook.com/" do
              %i.fa.fa-facebook-square.fa-lg.icon-facebook

      %li.main-fotter-cell.help-and-guid
        %h2.main-fotter__header
          ヘルプ＆ガイド
        %ul
          %li
            = link_to "#" do
              フリマガイド
          %li
            = link_to "#" do
              らくらくフリマ便
          %li
            = link_to "#" do
              ゆうゆうフリマ便
          %li
            = link_to "#" do
              梱包・発送たのメル便
          %li
            = link_to "#" do
              車体取引ガイド
          %li
            = link_to "#" do
              フリマあんしん・あんぜん宣言！
          %li
            = link_to "#" do
              偽ブランド品撲滅への取組
          %li
            = link_to "#" do
              フリマボックス
          %li
            = link_to "#" do
              スマホ出品・売却相場

      %li.main-fotter-cell.look-at-mercari
        %h2.main-fotter__header
          プライバシーと利用規約
        .look-at-mercari-box
          .look-at-mercari-left
          %ul
            %li
              = link_to "#" do
                プライバシーポリシー
            %li
              = link_to "#" do
                フリマ利用規約
            %li
              = link_to "#" do
                あんしんスマホサポート制度に関する利用特約
            %li
              = link_to "#" do
                コンプライアンスポリシー
          .look-at-mercari-right
          %ul
            %li
              = link_to "#" do
                個人データの安全管理に係る基本方針
            %li
              = link_to "#" do
                特定商取引に関する表記
            %li
              = link_to "#" do
                資金決済法に基づく表示
            %li
              = link_to "#" do
                法令順守と犯罪抑止の為に
          
      %li.main-fotter-cell.country
        %h2.main-fotter__header
          国
        %ul
          %li
            .jp
              = link_to "#" do
                日本
          %li
            .us
              = link_to "＃" do
                United States
  .main-footer-logo
    = link_to "#", class: "main-fotter-logo__icon" do
      =image_tag("/logo-white.png")
    %p.main-fotter-logo__copyright © 2020 FURIMA

app/views/items/_main-header.html.haml
.main-header
  .main-header__container
    %ul.main-header__container__logo-and-search
      %li.main-header__container__logo-and-search__logo
        = link_to image_tag('/logo.png', height:'40', width: '134', alt: "ロゴ１"), root_path
      %li.main-header__container__logo-and-search__search
        .main-header__container__logo-and-search__search__box
        = form_with url: search_items_path, method: :get, local: true do |f|
          .form-group
            = f.text_field :search, class: 'form-control'
          = button_tag type: 'submit', class: 'btn-primary' do
            = image_tag '/icon-search 1.png', alt: '', height: '36', width: '36', class: 'searchtest', id:'sbtn'
    %ul.lists.clearfix
      %li.lists__left.left-float
        .categories
          %h2
            = link_to "#" do
              %i.fa.fa-list-ul
                %span カテゴリーで探す
            
      %li.signin-and-signup.right-float
        %ul.account
          - if user_signed_in?
            %li.signin-btn
              = link_to "マイページ", "/users/#{current_user.id}", class: "signin-btn__mypage"
          - else
            %li.signin-btn
              = link_to "ログイン", user_session_path, class: "signin-btn__text"
            %li.signup-btn
              = link_to "新規会員登録", new_user_registration_path, class: "signup-btn__text"
          %end

app/views/items/destroy.html.haml
.contents.row
  .success
    %h3
      削除が完了しました。
    %a.btn{ :href => '/'} 投稿一覧へ戻る

app/views/items/edit.html.haml
.n__container
  .n__logo
    = link_to image_tag('/logo.png', :width => '170', :height => '60'), root_path
      
  .n__form__container
    =form_for @item do |f|
      %ul
        .n__image__container
          %p.message 商品出品画像（必須）
          %p.message 最大5枚までアップロード出来ます
          .post__drop__box__container
            .prev-content
              - @item.images.each do |image|
                .preview-box
                  .upper-box
                    = image_tag image.image.url, width: "112", height: "112", alt: "preview"
                  .lower-box
                    .delete-box
                      .delete-btn
                        %span 削除
            .label-content
              %label{for: "item_images_attributes_#{@item.images.length}_image", class: "label-box", id: "label-box--#{@item.images.length}"}
                %pre.label-box__text-visible クリックしてファイルをアップロード
            .hidden-content
              =f.fields_for :images do |i|
                = i.file_field :image, class: "hidden-field"
                = i.check_box :_destroy, class: "hidden-checkbox"
              - @item.images.length.upto(4) do |i|
                %input{name: "item[images_attributes][#{i}][image]", id: "item_images_attributes_#{i}_image", class: "hidden-field", type: "file"}
        .n__item__container
          %p.message 商品名（必須）
          = f.text_field :name, class: "name-box",  placeholder: "商品名（必須 40文字まで)"
          %p.message 商品の説明（必須）
          = f.text_area :text, class: "description-box",  cols: "60", rows: "7", placeholder: "商品の説明(必須1,000文字以内)(色、素材、重さ、定価、注意点など)                      例）2010年頃には一万円で購入したジャケットです。ライトグレーではありません。あわせやすいのでお勧めです。"
        .n__details__container
          %p.message 商品の詳細
          %p.message カテゴリー（必須)
          .sell-category-box
            = f.collection_select :category_id, @category_parent_array, :id, :name, {prompt: "", selected: @parent_category.id}, {class: 'sell__item-category', id: 'parent_category'}
            = f.collection_select :category_id, @child, :id, :name, {prompt: "", selected: @child_category.id}, {class: 'sell__item-category', id: 'child_category'}
            = f.collection_select :category_id, @grandchild, :id, :name, {}, {class: 'sell__item-category', id: 'grandchild_category'}

          %p.message ブランド (任意)
          = f.text_field :brand, class: "brand-box", placeholder: "例) シャネル"
          %p.message 商品の状態（必須）
          = f.collection_select :status_id, Status.all, :id, :name, {}, {class: "select-box"}
        .n__post__container
          %p.message 配送について
          %p.message 配送料の負担（必須）
          = f.collection_select :burden_id, Burden.all, :id, :name, {}, {class: "select-box"}
          %p.message 発送元の地域（必須）
          = f.collection_select :area_id, Area.all, :id, :name, {}, {class: "select-box"}
          %p.message 発送までの日数（必須）
          = f.collection_select :days_to_ship_id, DaysToShip.all, :id, :name, {}, {class:"select-box"}
        .n__price__container
          %p.message 価格（¥300〜9,999,999）
          .content-flex
            .message 販売価格（必須）
            .price
              %span ¥
              =f.number_field :selling_price, class: "item-price-title-text-b-field-text", min: "300", max: "9999999", placeholder: "0", id: "price_calc"
      .n__submit__container
        .button
          =f.submit "商品情報を編集する", class: "exhibition"
        .back
          = link_to "編集しないで戻る", item_path(@item.id)
      .n__attention__container
        %p.message 禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。
  .n__end__logo__container
    .n__end__logo__container__end__logo
      = link_to image_tag('/logo.png', :width => '170', :height => '60'), root_path
      %p ©️Frima.inc 

app/views/items/index.html.haml
.wrapper
  = render partial: 'items/item-btn'
  = render partial: 'items/main-header'
  .main1
    .main1__page
      .main1__title
        %h1 人生を変えるフリマアプリ
      .main1__subtitle
        %p FURIMAはだれでもかんたんに出品・購入できる
        %p フリマアプリです
      .main1__btn
        .main1__btn--apple
          = image_tag '/Download_on_the_App_Store_Badge_US-UK_RGB_blk_092917.svg',size: '180x53'
        .main1__btn--google
          = image_tag '/google-play-badge.png',size: '200x73'
  .main2
    .main2__page
      .main2__heading
        %h2 FURIMAが選ばれる3つの理由
      %ul.main2__title
        %li.main2__title__left
          = image_tag '/pict-reason-01.jpg',size: '280x280'
          %span 
            .main2__title__left--num
              1
          .main2__title__left--text
            %h3
              %span.spancolor 3分で
              すぐに出品
            .main2__title__left--text--sub
              %P スマホで入力するだけで簡単に出品できる！
        %li.main2__title__center
          = image_tag '/pict-reason-02.jpg',size: '280x280'
          %span
            .main2__title__center--num
              2
          .main2__title__center--text
            %h3
              %span.spancolor シンプル
              で使いやすい
            .main2__title__center--text--sub
              %p めんどくさい入力は必要なく、検索に購入もスムーズ！
        %li.main2__title__right
          = image_tag '/pict-reason-03.jpg',size: '280x280'
          %span
            .main2__title__right--num
              3
          .main2__title__right--text
            %h3
              手数料
              %span.spancolor 業界最安
            .main2__title__right--text--sub
              %p 最大3%でお得に出品&購入！
  .main3
    .main3__page
      .main3__title
        %h4 会員数日本一位
      .main3__subtitle
        %p FURIMAは、フリマアプリで最も人気。
        %p 出品・購入回数も業界最多です！
        %p ほしかったあの商品に出会えるかもしれません。
      .main3__btn
        .main3__btn--apple
          = image_tag '/Download_on_the_App_Store_Badge_US-UK_RGB_blk_092917.svg',size: '180x53'
        .main3__btn--google
          = image_tag '/google-play-badge.png',size: '200x73'
  .main4
    .main4__page
      .main4__heading
        %h2 FURIMAの特徴
      .main4__title
        .main4__title__left
          = image_tag '/icon-01.png',size: '154x237'
          .main4__title__left--text
            %h3 簡単に売り買いできる
          .main4__title__left--sub
            %P スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
        .main4__title__center
          = image_tag '/icon-03.png',size: '154x237'
          .main4__title__center--text
            %h3 売上金は即日振込みに対応
            .main4__title__center--text--sub
              %p 午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
        .main4__title__right
          = image_tag '/icon-04.png',size: '154x237'
          .main4__title__right--text
            %h3 様々な支払いに対応
            .main4__title__right--text--sub
              %p お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
  .main5
    .main5__page
      .main5__picupcategory
        %p ピックアップカテゴリー
      .main5__newlist
        %span.spancolor 新規投稿商品
      .main5__itemlist
        - @item.each do |item|
          .main5__itemlist--left
            .main5__itemlist--left--pic
            = link_to item_path(item.id), class:"Edit" do
              = image_tag item.images[0].image.url, width: '230', height: '180'
              .main5__itemlist--left--name
                = item.name
              .main5__itemlist--left--price
                = item.selling_price
                円
              .main5__itemlist--left--text
                (税込)
  .main6
    .main6__page
      .main6__title
        %h4 だれでもかんたん、人生を変えるフリマアプリ
      .main6__subtitle
        %p 今すぐ無料ダウンロード！
      .main6__btn
        .main6__btn--apple
          = image_tag '/Download_on_the_App_Store_Badge_US-UK_RGB_blk_092917.svg',size: '180x53'
        .main6__btn--google
          = image_tag '/google-play-badge.png',size: '200x73'

  = render partial: 'items/main-footer'

app/views/items/lady.html.haml
.wrapper
  = render partial: 'items/item-btn'
  = render partial: 'items/main-header'

  .search
    レディース一覧
    - @items.each do |item|
      .search-list
        %ul.search-list-box
          %li.search-list-box-left
            = link_to item_path(item.id), class:"search-show" do
              .search-list-box-left-pic
                = image_tag item.images[0].image.url, width: '100', height:'100'
              .search-list-box-left-price
                ¥
                = item.selling_price
                （税込）
          %li.search-list-box-right
            = link_to item_path(item.id), class:"search-show" do
              .search-list-box-right-name
                商品名：
                = item.name
              .search-list-box-right-text
                商品説明：
                = item.text

app/views/items/new.html.haml
= render 'form'

app/views/items/search.html.haml
.wrapper
  = render partial: 'items/item-btn'
  = render partial: 'items/main-header'

  .search
    検索結果
    - @items.each do |item|
      .search-list
        %ul.search-list-box
          %li.search-list-box-left
            = link_to item_path(item.id), class:"search-show" do
              .search-list-box-left-pic
                = image_tag item.images[0].image.url, width: '100', height:'100'
              .search-list-box-left-price
                ¥
                = item.selling_price
                （税込）
          %li.search-list-box-right
            = link_to item_path(item.id), class:"search-show" do
              .search-list-box-right-name
                商品名：
                = item.name
              .search-list-box-right-text
                商品説明：
                = item.text

app/views/items/show.html.haml
= render partial: 'main-header'
= render partial: 'items/item-btn'
.item-detail
  .item-detail__top
    .item-detail__top__box
      = link_to  root_path, class: 'submit-btn-link' do
        FURIMA
      %span　>　
      = link_to  lady_items_path, class: 'submit-btn-link' do
        = @item.category.parent.parent.name
      %span　>　
      = link_to  root_path, class: 'submit-btn-link' do 
        = @item.category.parent.name
      %span　>　
      = link_to  root_path, class: 'submit-btn-link' do
        = @item.category.name
      %span　>　
      = link_to  root_path, class: 'submit-btn-link' do
        = @item.name
      .item-detail__top__box__item-name 
        = @item.name
      .item-detail__top__box__item-image
        = image_tag @item.images[0].image.url, class: 'image-main', size: '400x400'
        %li.item-detail__top__box__item-image-sub
          - @item.images.each do |item|
            = image_tag item.image.url, class: 'image-sub', size: '60x60'
      .item-detail__top__box__item-price 
        .item-detail__top__box__item-price-box
          ¥
          = @item.selling_price
        .item-detail__top__box__item-price-detail
          (税込) 送料込み
      .item-detail__top__box__item-text
        .item-detail__top__box__item-text-box
          = simple_format @item.text
      .item-detail__table
        %table
          %tbody
            %tr
              %th 出品者
              %td
                = link_to "#", class: "nickname" do
                  = @item.saler.nickname
            %tr
              %th カテゴリー
              %td
                = link_to "#", class: "category" do
                  = @item.category.parent.parent.name
                %br
                = link_to "#", class: "category" do
                  = @item.category.parent.name
                %br
                = link_to "#", class: "category" do
                  = @item.category.name
            %tr
              %th ブランド
              %td
                = @item.brand
            %tr
              %th 商品の状態
              %td
                = @item.status.name
            %tr
              %th 配送料の負担
              %td
                = @item.burden.name
            %tr
              %th 発送元の地域
              %td
                = link_to '#', class: "area" do
                  = @item.area.name
            %tr
              %th 発送日の目安
              %td
                = @item.days_to_ship.name
      -if user_signed_in?
        - if current_user.id == @item.saler_id 
          .item-detail__management
            = link_to "商品の編集", edit_item_path, class:"edit"
            ／
            = link_to "この商品を削除する", item_path, method: :delete, class:"destroy"
        - else
          .item-detail__buy
            =link_to "商品購入画面に進む", buyers_path(@item.id), class: "btn"
      - else
        .item-detail__buy
          = link_to "ログインして購入画面に進む", new_user_session_path, class: "btn"
        
      .item-detail__nav
        - if @prev_item.present?
          .item-detail__nav-prev
            = link_to "< 前の商品", item_path(@prev_item), class:"nav"
        - if @next_item.present?
          .item-detail__nav-next
            = link_to "後ろの商品 >", item_path(@next_item),class:"nav-next"
            
      .more-nav
        = link_to "#{@item.saler.nickname}さんのその他の出品", "#", class:"more"
      .more-list
        .more-list__box
          - @my_item.order('created_at DESC').limit(6).each do |my_item|
            .more-list__box__item
              = link_to item_path(my_item) do
                = image_tag my_item.images[0].image.url, class: "image", size: '221x200'
                .more-list__box__item__text
                  .more-list__box__item__text-name
                    = link_to item_path(my_item) do
                      = my_item.name
                  .more-list__box__item__text-price
                    = link_to item_path(my_item) do
                      ¥   
                      = my_item.selling_price 
.link
  %link{href: "_show.scss", rel: "stylesheet", type: "scss"}
    .link-text
      %h2 だれでもかんたん、人生を変えるフリマアプリ
      %p 今すぐ無料ダウンロード！
      .link-icon
        = image_tag '/Download_on_the_App_Store_Badge_US-UK_RGB_blk_092917.svg', class:"icon"
        = image_tag '/google-play-badge.png', class: "icon-goo", size: '200x80'
= render partial: 'main-footer'

app/views/items/update.html.haml
.contents.row
  .success
    %h3
      更新が完了しました。
    %a.btn{:href => "/"} 投稿一覧へ戻る