config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'
  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
      get 'lady'
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      resources :buyers, only: [:index] do
        collection do
          post 'pay', to: 'buyers#pay'
          get 'done', to: 'buyers#done'
        end
      end
    end
  end
  resources :users, only: [:show, :edit]
  resources :addresses, only: [:new, :create]
  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  validates  :customer_id, :card_id, presence: true
  belongs_to :user
end

app/controllers/card_controller.rb
class CardController < ApplicationController

  require "payjp"

  def new
    card = Card.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end

  def pay #payjpとCardのデータベース作成を実施します。
    Payjp.api_key = Rails.application.credentials[:PAYJP_PRIVATE_KEY]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      description: '登録テスト', #なくてもOK
      email: current_user.email, #なくてもOK
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      ) #念の為metadataにuser_idを入れましたがなくてもOK
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete #PayjpとCardデータベースを削除します
    card = Card.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key = Rails.application.credentials[:PAYJP_PRIVATE_KEY]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to action: "new"
  end

  def show #Cardのデータpayjpに送り情報を取り出します
    card = Card.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = Rails.application.credentials[:PAYJP_PRIVATE_KEY]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end
end

app/helpers/card_helper.rb
module CardHelper
end

app/views/card/new.html.haml
.container
  = render "items/main-header"
  .mypage
    .mypage__main
      = render "modules/mypage-left"
    
      .credit-container
        .credit-container__header
          クレジットカード情報入力
          
        .card-form
          = form_tag(pay_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
            .card-form__number          
              %label{class:'group--label', for: 'card_number'}  カード番号
              %span.input-required
                必須
              %br

              = text_field_tag "number", "", class: "card-number--input", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
              .registration-error{type: "hidden", value: "必須項目です"}
              %ul.card-list
                %li.card-list--item{ style: "margin-left: 0;"}
                  = image_tag "/visa.svg", width:"60", height:"30"
                %li.card-list--item
                  = image_tag "/mastercard.svg", width:"60", height:"30"
                %li.card-list--item
                  = image_tag "/jcb.svg", width:"60", height:"30"
                %li.card-list--item
                  = image_tag "/amex.svg", width:"60", height:"30"
                %li.card-list--item
                  = image_tag "/diners.svg", width:"60", height:"30"      

            .card-form__expire
              %label.group--label 有効期限
              %span.input-required
                必須
              .card-expire
                .card-expire__select-month
                  %select#exp_month{name: "exp_month", type: "text"}
                    %option{value: ""} --
                    %option{value: "1"}01
                    %option{value: "2"}02
                    %option{value: "3"}03
                    %option{value: "4"}04
                    %option{value: "5"}05
                    %option{value: "6"}06
                    %option{value: "7"}07
                    %option{value: "8"}08
                    %option{value: "9"}09
                    %option{value: "10"}10
                    %option{value: "11"}11
                    %option{value: "12"}12
                  %i.fa.fa-angle-down
                  %span{class: "month"} 月
                .card-expire__select-year
                  %select#exp_year{name: "exp_year", type: "text"}
                    %option{value: ""} --
                    %option{value: "2020"}20
                    %option{value: "2021"}21
                    %option{value: "2022"}22
                    %option{value: "2023"}23
                    %option{value: "2024"}24
                    %option{value: "2025"}25
                    %option{value: "2026"}26
                    %option{value: "2027"}27
                    %option{value: "2028"}28
                    %option{value: "2029"}29
                  %i.fa.fa-angle-down
                  %span{class:"year"} 年

            .card-form__security-code
              %label.group--label{for: "cvc"} セキュリティコード
              %span.input-required
                必須
              = text_field_tag "cvc", "", class: 'payment__security-code', type: "text", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
              .question-form
                %span.question-form__mark ?
                %span.question-form__text 
                  カード裏面の番号とは？
              #card_token
              = submit_tag "追加する", class: "card-form__add", id: "token_submit", type: 'button'

  = render 'items/main-footer'

app/views/card/show.html.haml
.container
  = render "items/main-header"
  .mypage
    .mypage__main
      = render "modules/mypage-left"
    
      .credit-container
        .credit-container__header
          クレジットカード情報入力
          
        .card-form
          .card-form__number
            %label{class:'group--label', for: 'card_number'} 登録クレジットカード情報
            %br
            = "**** **** **** " + @default_card_information.last4
            %br
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
            = form_tag(delete_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
              %input{ type: "hidden", name: "card_id", value: "" }
              %button 削除する
  = render 'items/main-footer'